- name: Install Docker
  become: yes
  hosts: swarm
  roles:
    - docker

- name: Setup master node
  become: yes
  hosts: master
  roles:
    - swarm-master

- name: Setup worker node
  become: yes
  hosts: worker
  roles:
    - swarm-worker