- name: Initialize Docker Swarm
  command: docker swarm init
  register: docker_swarm_init_output 

- name: Create file with output 
  copy:
    content: "{{ docker_swarm_init_output.stdout }}"
    dest: /root/dockerswarminit

- name: Prepare script Swarm 
  shell: sed -n '5p' /root/dockerswarminit > /root/swarmjoin.sh

- name: Get Swarmjoin 
  fetch:
    dest: ./join
    src: /root/swarmjoin.sh

- name: Organize Files
  shell: |
         cp join/{{ inventory_hostname }}/root/swarmjoin.sh join/ 
         rm -fr join/{{ inventory_hostname }}
  delegate_to: localhost
  become: no