- name: Disable SELinux 
  selinux:
    state: disabled

- name: Install repo
  dnf: 
    name: https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-4.el8.noarch.rpm
    state: present 
    disable_gpg_check: yes 

- name: Install packages
  dnf:
    name: "{{ item }}"
  loop: "{{ zabbix_packages }}"

- name: Check that the server.sql.gz exists
  stat:
    path: /usr/share/doc/zabbix-sql-scripts/mysql/server.sql.gz
  register: create_sql_gz_exist

- name: Unarchive server.sql.gz
  command: gunzip /usr/share/doc/zabbix-sql-scripts/mysql/server.sql.gz
  when: create_sql_gz_exist.stat.exists

- name: Import mysql
  shell: "mysql -h {{ DBHost }} -u{{ DBName }} -p{{ DBPassword }} zabbix < /usr/share/doc/zabbix-sql-scripts/mysql/server.sql"

- name: Config zabbix_server.conf
  template:
    src: zabbix_server.conf
    dest: /etc/zabbix/zabbix_server.conf

- name: Start services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ services }}"

