- name: Disable SELinux 
  selinux:
    state: disabled

- name: Install repo
  dnf: 
    name: https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-4.el8.noarch.rpm
    state: present 
    disable_gpg_check: yes 

- name: Install packages
  dnf:
    name: "{{ item }}"
  loop: "{{ zabbix_packages }}"

- name: Create user Apache e Nginx
  ansible.builtin.user:
    name: "{{ item }}"
  loop: "{{ users }}"

- name: Create path
  file:
    path: /var/www/html
    state: directory

- name: Config zabbix_conf.php
  template:
    src: zabbix.conf.php
    dest: /etc/zabbix/web/zabbix.conf

- name: Start services
  service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  loop: "{{ services }}"

